### ISSUE TITLE
Error: Unable to resolve action `char0n/swagger-editor-validate@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by craigpastro** [char0n/swagger-editor-validate#109]
**Describe the bug**

👋 I have the following in my github action:
```
jobs:
  validate-swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: service.swagger.json
```
but when the action runs I get an error
```
Error: Unable to resolve action `char0n/swagger-editor-validate@v1`, unable to find version `v1`
```

I am not sure if I am doing something wrong?

**To Reproduce**

As above I suppose.

**Expected behavior**

I expect that github actions should resolve the action, send my swagger to https://editor.swagger.io/ for validation, and hopefully, in my case, fail validation.

**Screenshots**

**Additional context**

- Version: v1
- Platform: github actions
- Subsystem:

Thank you!
